# For more info about configuring dependabot:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # (Poetry)
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # (Github actions)
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
